<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Launch Application]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="117540" started-at="2018-05-08T12:54:31Z" finished-at="2018-05-08T12:56:28Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="117540" started-at="2018-05-08T12:54:31Z" finished-at="2018-05-08T12:56:28Z">
      <class name="test.CheckoutTest">
        <test-method status="FAIL" signature="GuestUser_CheckoutFlow(helper.DataEntity)[pri:0, instance:test.CheckoutTest@72d818d1]" name="GuestUser_CheckoutFlow" duration-ms="117508" started-at="2018-05-08T18:24:31Z" data-provider="checkOutData" finished-at="2018-05-08T18:26:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[helper.DataEntity@6ebc05a6]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utils.CustomUtils.setup(CustomUtils.java:70)
	at helper.User.getFactory(User.java:12)
	at test.CheckoutTest.GuestUser_CheckoutFlow(CheckoutTest.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[Launch Application]]>
            </line>
          </reporter-output>
        </test-method> <!-- GuestUser_CheckoutFlow -->
      </class> <!-- test.CheckoutTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
